

 
// *Vcc is connected on servo pod pin 7
 //*Vdd is connected on servo pod pin 6
 //*Output of the sensor is connected to PD0 (INT0) of Atmega 2560 i.e Pin 20 on expansion slot
 //*S0 of the sensor is connected to PD4 of Atmega 2560 i.e Pin 25 on expansion slot
 //*S1 of the sensor is connected to PD5 of Atmega 2560 i.e Pin 29 on expansion slot
 //*S2 of the sensor is connected to PD6 of Atmega 2560 i.e Pin 33 on expansion slot
 //*S3 of the sensor is connected to PD7 of Atmega 2560 i.e Pin 34 on expansion slot


#define F_CPU 14745600
#include <avr/io.h>
#include <avr/interrupt.h>
#include <util/delay.h>
#include <math.h> //included to support power function
#include "lcd.c"

volatile unsigned long int pulse = 0; //to keep the track of the number of pulses generated by the color sensor
volatile unsigned long int red;       // variable to store the pulse count when read_red function is called
volatile unsigned long int blue;      // variable to store the pulse count when read_blue function is called
volatile unsigned long int green;     // variable to store the pulse count when read_green function is called

void lcd_port_config (void)
{
	DDRC = DDRC | 0xF7; //setting all the LCD pin's direction set as output
	PORTC = PORTC & 0x80; //setting all the LCD pins are set to logic 0 except PORTC 7
}

void color_sensor_pin_config(void)
{
	DDRD  = DDRD | 0xFE; //set PD0 as input for color sensor output
	PORTD = PORTD | 0x01;//Enable internal pull-up for PORTD 0 pin
}

void port_init(void)
{
	lcd_port_config();//lcd pin configuration
	color_sensor_pin_config();//color sensor pin configuration
}

void color_sensor_pin_interrupt_init(void) //Interrupt 0 enable
{
	cli(); //Clears the global interrupt
	EICRA = EICRA | 0x02; // INT0 is set to trigger with falling edge
	EIMSK = EIMSK | 0x01; // Enable Interrupt INT0 for color sensor
	sei(); // Enables the global interrupt
}

//ISR for color sensor
ISR(INT0_vect)
{
	pulse++; //increment on receiving pulse from the color sensor
}

void init_devices(void)
{
	cli(); //Clears the global interrupt
	port_init();  //Initializes all the ports
	color_sensor_pin_interrupt_init();
	sei();   // Enables the global interrupt
}

//Filter Selection
void filter_red(void)    //Used to select red filter
{
	//Filter Select - red filter
	PORTD = PORTD & 0xBF; //set S2 low
	PORTD = PORTD & 0x7F; //set S3 low
}

void filter_green(void)	//Used to select green filter
{
	//Filter Select - green filter
	PORTD = PORTD | 0x40; //set S2 High
	PORTD = PORTD | 0x80; //set S3 High
}

void filter_blue(void)	//Used to select blue filter
{
	//Filter Select - blue filter
	PORTD = PORTD & 0xBF; //set S2 low
	PORTD = PORTD | 0x80; //set S3 High
}

void filter_clear(void)	//select no filter
{
	//Filter Select - no filter
	PORTD = PORTD | 0x40; //set S2 High
	PORTD = PORTD & 0x7F; //set S3 Low
}

//Color Sensing Scaling
void color_sensor_scaling()		//This function is used to select the scaled down version of the original frequency of the output generated by the color sensor, generally 20% scaling is preferable, though you can change the values as per your application by referring datasheet
{
	//Output Scaling 20% from datasheet
	//PORTD = PORTD & 0xEF;
	PORTD = PORTD | 0x10; //set S0 high
	//PORTD = PORTD & 0xDF; //set S1 low
	PORTD = PORTD | 0x20; //set S1 high
}

void red_read(void) // function to select red filter and display the count generated by the sensor on LCD. The count will be more if the color is red. The count will be very less if its blue or green.
{
	//Red
	filter_red(); //select red filter
	pulse=0; //reset the count to 0
	_delay_ms(100); //capture the pulses for 100 ms or 0.1 second
	red = pulse;  //store the count in variable called red
	
	lcd_cursor(1,1);  //set the cursor on row 1, column 1
	lcd_string("Red Pulses"); // Display "Red Pulses" on LCD
	lcd_print(2,1,red,5);  //Print the count on second row
	_delay_ms(1000);	// Display for 1000ms or 1 second
	lcd_wr_command(0x01); //Clear the LCD
}

void green_read(void) // function to select green filter and display the count generated by the sensor on LCD. The count will be more if the color is green. The count will be very less if its blue or red.
{
	//Green
	filter_green(); //select green filter
	pulse=0; //reset the count to 0
	_delay_ms(100); //capture the pulses for 100 ms or 0.1 second
	green = pulse;  //store the count in variable called green
	
	lcd_cursor(1,1);  //set the cursor on row 1, column 1
	lcd_string("Green Pulses"); // Display "Green Pulses" on LCD
	lcd_print(2,1,green,5);  //Print the count on second row
	_delay_ms(1000);	// Display for 1000ms or 1 second
	lcd_wr_command(0x01); //Clear the LCD
}

void blue_read(void) // function to select blue filter and display the count generated by the sensor on LCD. The count will be more if the color is blue. The count will be very less if its red or green.
{
	//Blue
	filter_blue(); //select blue filter
	pulse=0; //reset the count to 0
	_delay_ms(100); //capture the pulses for 100 ms or 0.1 second
	blue = pulse;  //store the count in variable called blue
	
	lcd_cursor(1,1);  //set the cursor on row 1, column 1
	lcd_string("Blue Pulses"); // Display "Blue Pulses" on LCD
	lcd_print(2,1,blue,5);  //Print the count on second row
	_delay_ms(1000);	// Display for 1000ms or 1 second
	lcd_wr_command(0x01); //Clear the LCD
}
void color_read(void)
{
	//Color
	
	
	//Red
	filter_red(); //select red filter
	pulse=0; //reset the count to 0
	_delay_ms(1000); //capture the pulses for 100 ms or 0.1 second
	red = pulse;  //store the count in variable called red
	
	lcd_cursor(1,1);  //set the cursor on row 1, column 1
	lcd_string("R"); // Display "Red Pulses" on LCD
	lcd_print(1,3,red,5);  //Print the count on second row
	_delay_ms(100);// Display for 1000ms or 1 second
    //Clear the LCD
    
	
	//Green
	filter_green(); //select green filter
	pulse=0; //reset the count to 0
	_delay_ms(1000); //capture the pulses for 100 ms or 0.1 second
	green = pulse;  //store the count in variable called green
	
	lcd_cursor(1,9);  //set the cursor on row 1, column 1
	lcd_string("G"); // Display "Green Pulses" on LCD
	lcd_print(1,11,green,5);  //Print the count on second row
	_delay_ms(100);// Display for 1000ms or 1 second
   //Clear the LCD
	
	
	//Blue
	filter_blue(); //select blue filter
	pulse=0; //reset the count to 0
	_delay_ms(1000); //capture the pulses for 100 ms or 0.1 second
	blue = pulse;  //store the count in variable called blue
	
	lcd_cursor(2,1);  //set the cursor on row 1, column 1
	lcd_string("B"); // Display "Blue Pulses" on LCD
	lcd_print(2,3,blue,5);  //Print the count on second row
	_delay_ms(100);	// Display for 1000ms or 1 second
	 //Clear the LCD
}
void red_show()
{
	lcd_wr_command(0x01); //Clear the LCD
	lcd_cursor(1,4);  //set the cursor on row 1, column 4
	lcd_string("RED"); // Display " RED" on LCD
	_delay_ms(100);	// Display for 1000ms or 1 second
}
void green_show()
{
	lcd_wr_command(0x01); //Clear the LCD
	lcd_cursor(1,4);  //set the cursor on row 1, column 4
	lcd_string("GREEN"); // Display " GREEN" on LCD
	_delay_ms(100);	// Display for 1000ms or 1 second
}
void blue_show()
{
	lcd_wr_command(0x01); //Clear the LCD
	lcd_cursor(1,4);  //set the cursor on row 1, column 4
	lcd_string("BLUE"); // Display " BLUE" on LCD
	_delay_ms(100);	// Display for 1000ms or 1 second
}
int main(void)
{
    init_devices();
    lcd_set_4bit();
    lcd_init();
	color_sensor_scaling();
	
	while(1)
    {
       color_read(); //display the pulse count 
    
    if((red<=0 && red>=50000 )&&(green<=000 && green>=50000)&&(blue<=000 && blue>=50000))
    	blue_show();
    if((red<=26000 && red>=31000 )&&(green<=12000 && green>=18000)&&(blue<=13000 && blue>=18000))
    	red_show();
	if((red<=17000 && red>=23000 )&&(green<=12000 && green>=15000)&&(blue<=12000 && blue>=15000))
    	green_show();
	}
	return 0;
}
